GET http://localhost:3001/api/bloglist/
###
# Get all blogs

POST http://localhost:3001/api/bloglist/
Content-Type: application/json  

{
  "title": "New Blog Post2",
  "author": "Mon",
  "url": "http://example.com/new-blog-post",
  "likes": 10
}
###
# Create a new blog post
GET http://localhost:3001/api/bloglist/69b325ed396b8ca2be2c3284
###
# Get a specific blog post by ID (replace 69b1b593bcf8fc2063a036be with the actual ID)
DELETE http://localhost:3001/api/bloglist/69b325ed396b8ca2be2c3284
###
# Delete a specific blog post by ID (replace 69b1b593bcf8fc2063a036be with the actual ID)
PUT http://localhost:3001/api/bloglist/69b32621d4fda9d55d6f7575
Content-Type: application/json

{
  "title": "Updated Blog Post",
  "author": "Mon",
  "url": "http://example.com/updated-blog-post",
  "likes": 20
}
###
# Update a specific blog post by ID (replace 69b1b593bcf8fc2063a036be with the actual ID)

POST http://localhost:3001/api/users/
Content-Type: application/json

{
  "username": "elloworld",
  "name": "hello",
  "password": "password"
} 
###
# Create a new user
GET http://localhost:3001/api/users/
###

POST http://localhost:3001/api/login/
Content-Type: application/json

{
  "username": "elloworld",
  "password": "password"
}
###
# Login with the created user and get a token
POST http://localhost:3001/api/login/
Content-Type: application/json

{
  "username": "elloworld",
  "password": "password"
}
###
# Login with the created user and get a token, then use the token to create a new blog post

POST http://localhost:3001/api/bloglist/
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImVsbG93b3JsZCIsImlkIjoiNjliYjc2OTc4MTZmMmZkMWJlNjdlNGI3IiwiaWF0IjoxNzc0MDI0MzA3LCJleHAiOjE3NzQwMjUyMDd9.VqrdiVM8vK0nH49_athxDZLyW9pAgyEXGorBDnx59_0

{
  "title": "Lol this is a new blog post with author not valid", 
  "author": "lol",
  "url": "http://example.com/new-blog-post-with-token",
  "likes": 15
}
###
# Create a new blog post with token authentication
