const express = require('express')
const mongoose = require('mongoose')
const config = require('./utils/config')
const logger = require('./utils/logger')
const middleware = require('./utils/middleware')
const blogRouter = require('./controllers/blog')
const userRouter = require('./controllers/users')  
const loginRouter = require('./controllers/login')
const RefreshTokenRouter = require('./controllers/refresh-token')
const app = express()
logger.info(`connecting to ${config.MONGODB_URI}`)
mongoose.connect(config.MONGODB_URI, {family: 4})
    .then(() => {
        logger.info('connected to mongodb')
    }).catch(err => {
        logger.error(`error connection to mongodb: ${err.message}`)
    })
app.use(express.static('dist'))
app.use(express.json())
app.use('/api/login', loginRouter)
app.use('/api/refresh-token', RefreshTokenRouter)
app.use(middleware.requestLogger)
app.use('/api/bloglist', blogRouter)
app.use('/api/users', userRouter)
app.use(middleware.unknownEndPoint)
app.use(middleware.errorHandler)
module.exports = app